### PR TITLE
MQTT Support

### PR DESCRIPTION
**Pull request by andig**
Add mqtt as per https://github.com/gonium/gosdm630/pull/22

### CODE REVIEW

**Comment by dimagoltsman** [comment]
any chance this will be merged? i would really really like to use this, perfect for smart home

**Comment by andig** [comment]
@dimagoltsman it seems this repo is currently not receiving any updates. I'm in the process of providing a clean fork at http://github.com/andig/gosdm630. 

I'm looking to implement:

  - websockets instead of longpolling (pretty much done)
  - mqtt support (not started)

**Comment by dimagoltsman** [comment]
sounds great!
waiting for the mqtt, using it for smart home...

**Comment by andig** [comment]
See https://github.com/gonium/gosdm630/pull/39 for a better version that does *not* depend on the longpolling api but subscribes directly to the meter updates.

**Pull request closed without merging**
